### Add User
POST localhost:8080/user/
Content-Type: application/json;

{
  "address": "Hai Phong",
  "email": "dothibichthuy_t65@hus.edu.vn",
  "fullname": "Do Bich Thuy",
  "level": 2,
  "mobile": "0379371432",
  "username": "Thuy124",
  "password": "020602",
  "role": 0,
  "status": 1
}


### List User
GET localhost:8080/user/
Accept: application/json

### Get One User
### Delete Product
< {%
    request.variables.set("id", "3")
%}
GET localhost:8080/user/{{id}}


### Update User
< {%
    request.variables.set("id", "3")
%}
PUT localhost:8080/user/{{id}}
Content-Type: application/json

{
  "address": "Hai Phong",
  "email": "dothibichthuy_t69@hus.edu.vn",
  "fullname": "Do Bich Thuy",
  "level": 2,
  "mobile": "0379371432",
  "username": "Thuy124",
  "password": "020602",
  "role": 0,
  "status": 1
}

###  Delete User
< {%
    request.variables.set("id", "3")
%}
DELETE localhost:8080/user/{{id}}




