spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/weblearnel
    username: root
    password: 0987269208tr
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  swagger:
    enabled: true
    title: " Web Learning API"
    description: " Web Learning API Documentation"
    version: "1.0.0"
    resource-pkg: "com.eazybytes.weblearnel"

server:
  port: 8082




